### ISSUE TITLE
facilities h-tag spacing 

### ISSUE THREAD

**Issue by iobami** [hngi/Team-Incredible-FE-Hotel-Bami#38]
![hotel-facilites](https://user-images.githubusercontent.com/36917979/84208105-e0267380-aaaa-11ea-9cb8-0055451dcecf.png)

![hotel-faci](https://user-images.githubusercontent.com/36917979/84208147-fe8c6f00-aaaa-11ea-8653-17f3d4925a3e.png)

@LolaMedina @pidoxy

**Comment by pidoxy** [comment]
What screen is this please?

**Comment by LolaMedina** [comment]
Facilities, the first two sections.

**Comment by LolaMedina** [comment]
![image](https://user-images.githubusercontent.com/56541025/84523405-2b6d9b80-acd0-11ea-8c40-d4d7806f6d94.png)![image](https://user-images.githubusercontent.com/56541025/84523423-3294a980-acd0-11ea-85a9-1a2ebadbcfbf.png)
