### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by bamiogunfemi** [hngi/Team-Incredible-FE-Hotel-Bami#6]

**Comment by tosinibrahim96** [comment]
#17

**Comment by ayodelekings** [comment]
[](https://drive.google.com/file/d/1ZxLF9aGR1bwfMzbQZ9RnW2y5-oNad1Zp/view?usp=sharing)

**Comment by ayodelekings** [comment]
![header2](https://user-images.githubusercontent.com/66247421/84539046-a643b000-acea-11ea-8075-e1c7f26fad16.png)
![header1](https://user-images.githubusercontent.com/66247421/84539051-a774dd00-acea-11ea-9f30-e11cfc9d41e9.png)

**Comment by tosinibrahim96** [comment]
<img width="948" alt="header1" src="https://user-images.githubusercontent.com/22124878/84544749-d04e9f80-acf5-11ea-816b-d9660287f95e.PNG">
