### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by bamiogunfemi** [hngi/Team-Incredible-FE-Hotel-Bami#7]

**Comment by iobami** [comment]
![hotel-iobami](https://user-images.githubusercontent.com/36917979/84534116-45fc4080-ace1-11ea-9df7-30f23c36466d.png)
![hotel-iobami1](https://user-images.githubusercontent.com/36917979/84534127-4a285e00-ace1-11ea-9f1f-ca0e8ecc8cc3.png)



CUSTOMER SECTION HOME PAGE

**Comment by Sproff** [comment]
I designed the special deals section and fixed all responsiveness 
![sam1](https://user-images.githubusercontent.com/61986442/84540448-400c5c80-aced-11ea-8874-dd758077f287.JPG)
![sam2](https://user-images.githubusercontent.com/61986442/84540450-41d62000-aced-11ea-957f-041769e37475.JPG)

![sam7](https://user-images.githubusercontent.com/61986442/84544138-97fa9180-acf4-11ea-9dca-5bf7bb6d43fc.JPG)
![sam8](https://user-images.githubusercontent.com/61986442/84544143-992bbe80-acf4-11ea-9aba-e9e507fd275e.JPG)

**Comment by Syndee** [comment]
![IMG_4891](https://user-images.githubusercontent.com/54890425/84546272-ead64800-acf8-11ea-8af8-e2b4763d1a2d.PNG)
![IMG_4892](https://user-images.githubusercontent.com/54890425/84546290-f590dd00-acf8-11ea-904f-9240f1eb1bc4.PNG)
![IMG_4893](https://user-images.githubusercontent.com/54890425/84546299-fa559100-acf8-11ea-9c81-b805ba504653.PNG)
