### ISSUE TITLE
Suites-and-rooms Page

### ISSUE THREAD

**Issue by bamiogunfemi** [hngi/Team-Incredible-FE-Hotel-Bami#8]

**Comment by iobami** [comment]
![hotel-iobami2](https://user-images.githubusercontent.com/36917979/84533996-15b4a200-ace1-11ea-9a8f-8720a5bbc17a.png)
![hotel-iobami3](https://user-images.githubusercontent.com/36917979/84534020-1baa8300-ace1-11ea-93e7-953dcc4d5107.png)

**Comment by Sproff** [comment]
Superb!

**Comment by Sproff** [comment]
I designed the rooms and suites section,
![sam3](https://user-images.githubusercontent.com/61986442/84540269-dd1ac580-acec-11ea-9a1b-7b9032d20cbe.JPG)
![sam4](https://user-images.githubusercontent.com/61986442/84540284-df7d1f80-acec-11ea-8ef9-086d8be63a28.JPG)
![sam5](https://user-images.githubusercontent.com/61986442/84540285-e015b600-acec-11ea-992c-bdb3394e7ede.JPG)
![sam6](https://user-images.githubusercontent.com/61986442/84540288-e0ae4c80-acec-11ea-88ce-316547be7364.JPG)



 hot-deals section
