### ISSUE TITLE
Facilities Page

### ISSUE THREAD

**Issue by bamiogunfemi** [hngi/Team-Incredible-FE-Hotel-Bami#9]

**Comment by LolaMedina** [comment]
![image](https://user-images.githubusercontent.com/56541025/84523166-c4e87d80-accf-11ea-89ad-fe76f5f75f75.png)

**Comment by pidoxy** [comment]
![image](https://user-images.githubusercontent.com/56538561/84524242-9075c100-acd1-11ea-9f9b-e7993feceeb6.png)
